### ISSUE TITLE
Support for docker-compose

### ISSUE THREAD

**Issue by AlexZeitler** [thenativeweb/crew#1]
Hi,

`crew` is a pretty nice lib :+1: 

Have you ever thought about support for `docker-compose`?

When having a Microservices scenario it is pretty likely to use `docker-compose` instead of linking containers manually. 

On the other hand from what I see, `Dockerode` does not support `docker-compose` and there doesn't seem to be a lib on npm which supports `docker-compose` at the moment.

**Comment by goloroden** [comment]
First of all: Thanks a lot for your nice words, and I really appreciate that you like our module :-)

Wrt your question, we have *actually* thought about this and actively decided against using `docker-compose`. But first of all, let's make clear, that using `docker-compose` may mean two things:

- Using the tool itself by calling out to the command-line instead of making REST API calls.
- Using the `.yml` file that is also being used by `docker-compose`.

Let me answer them separately:

### Why we use REST instead of the CLI

We have thought about this, more than once ;-). The problem basically comes down to the need to ship the tool for multiple platforms, which highly increases the module's size. Additionally, we then have to think about the license (and we need to watch the license for changes). All in all this makes things heavy and complicated. By using the REST API we are more lightweight, and far more flexible.

Additionally, internally we are in the need of setting up things in a way that are beyond `docker-compose`'s scope, e.g. by dynamically choosing the names of the containers created. Hence we would have to use the REST API anyway.

### Why we do not use the `.yml` file

This very last point is the reason, too, why we do not use the `.yml` file. There are too many things that can not be expressed in this file, currently, such as dynamic names for the containers.

### Summary

So… I think that you are right that there is no module that supports `docker-compose` right now, and we have thought about this, but we have decided against it for flexibility and ease of use.

Does this answer your question?

**Comment by goloroden** [comment]
PS: You also had an indirect question, the one about manually linking… I'm not perfectly sure whether I got it, but I guess you mean that you have to watch out in which order to start the containers so that links do work and are up and running.

We solve this by setting the restart policy to `always` (which in crew is `true`), and let the containers figure out the correct order by themself.

Does this help you?

**Comment by AlexZeitler** [comment]
Thanks for your explanation.
After thinking about it for a while I guess I won't need compose-support after all.
